<a href="https://colab.research.google.com/github/fikriyaeka/Datamining/blob/master/Datamining_C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 NAMA : FIKRIYA EKA WAHYUNI

>


NIM  : 192410101003

> 


KELAS: Datamining C 

In [ ]:
import numpy as np
arr1f = np.array([4,4,5,7,6,4,9,7,4,6,3,7]).reshape(4,3)
print("KODE 1F\n\"Buatlah Array 2D berikut menggunakan numpy\"\n")
print(arr1f)

KODE 1F
"Buatlah Array 2D berikut menggunakan numpy"

[[4 4 5]
 [7 6 4]
 [9 7 4]
 [6 3 7]]


In [ ]:
arr1g = np.array([7,8,5,4,7,7,7,1,9,5,4,10,2,1,2,9,8,5,3,7,3,4,9,9,2,9,3,2,4,8,1,6,6,8,1,3]).reshape(3,4,3)
print("KODE 1G\n\"Buatlah Array 3D berikut menggunakan numpy\"\n")
print(arr1g)

KODE 1G
"Buatlah Array 3D berikut menggunakan numpy"

[[[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]]


In [ ]:
arr2d = np.array([1,8,8,2,8,2,1,2,10,1,4,7,1,4,7,8,8,2,3,4]).reshape(5,4)
print("KODE 2D\n\"Tambahkan angka 1 pada setiap bilangan di baris ganjil array berikut. kemudian tambahkan angka 2 pada setiap bilangan di kolom genap array berikut \"\n")
print(arr2d)

arr2d[1::2]+=1
arr2d[:,::2]+=2

print("\n{SETELAH DITAMBAH}\n")
print(arr2d)

KODE 2D
"Tambahkan angka 1 pada setiap bilangan di baris ganjil array berikut. kemudian tambahkan angka 2 pada setiap bilangan di kolom genap array berikut "

[[ 1  8  8  2]
 [ 8  2  1  2]
 [10  1  4  7]
 [ 1  4  7  8]
 [ 8  2  3  4]]

{SETELAH DITAMBAH}

[[ 3  8 10  2]
 [11  3  4  3]
 [12  1  6  7]
 [ 4  5 10  9]
 [10  2  5  4]]


In [ ]:
arr2e=arr1g.copy()
print("KODE 2E\n\"Baliklah sumbu z array 3D berikut \"\n")
print(arr2e)
arr2e=np.flipud(arr2e)
print("\n{SETELAH DIBALIK}\n")
print(arr2e)

KODE 2E
"Baliklah sumbu z array 3D berikut "

[[[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]]

{SETELAH DIBALIK}

[[[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]]


In [ ]:
arr2f = arr2e.reshape(6,6)
print("KODE 2F\n\"Ubahlah array pada soal e menadi array 2D berukuran 6 x 6  \"\n")
print(arr2f)

KODE 2F
"Ubahlah array pada soal e menadi array 2D berukuran 6 x 6  "

[[ 2  9  3  2  4  8]
 [ 1  6  6  8  1  3]
 [ 2  1  2  9  8  5]
 [ 3  7  3  4  9  9]
 [ 7  8  5  4  7  7]
 [ 7  1  9  5  4 10]]


In [ ]:
arr3e = np.array([5,10,10,7,7,8,4,10,9,10,2,5,1,8,9,3,6,10,5,2,4,6,9,4]).reshape(6,4)
print("KODE 3E\n\"Ubahlah matrix kiri menjadi matrix sebelah kanan  \"\n")
print(arr3e)
new = arr3e.copy()
arr3e[0:3,0:2],arr3e[3:6,2:4],arr3e[3:6,0:2],arr3e[0:3,2:4]=new[3:6,2:4],new[0:3,0:2],new[0:3,2:4],new[3:6,0:2]
print("\n{SETELAH DIUBAH}\n")
print(arr3e)

KODE 3E
"Ubahlah matrix kiri menjadi matrix sebelah kanan  "

[[ 5 10 10  7]
 [ 7  8  4 10]
 [ 9 10  2  5]
 [ 1  8  9  3]
 [ 6 10  5  2]
 [ 4  6  9  4]]

{SETELAH DIUBAH}

[[ 9  3  1  8]
 [ 5  2  6 10]
 [ 9  4  4  6]
 [10  7  5 10]
 [ 4 10  7  8]
 [ 2  5  9 10]]
